import { Injectable } from "@angular/core";

@Injectable()
export class GlobalVars {
  public hideFooter: true;

  public bo_global_known_measures = [
    "box",
    "bunch",
    "can",
    "cans",
    "carton",
    "clove",
    "cloves",
    "cup",
    "cups",
    "dash",
    "drop",
    "drops",
    "each",
    "extra large",
    "gallon",
    "gallons",
    "gram",
    "grams",
    "head",
    "heads",
    "kg",
    "kgs",
    "large",
    "lb",
    "lb.",
    "lbs.",
    "medium",
    "ml",
    "ounce",
    "ounces",
    "oz",
    "oz.",
    "ozs",
    "pack",
    "package",
    "pinch ",
    "pint",
    "pints",
    "pound",
    "pounds",
    "quart",
    "quarts",
    "slice",
    "slices",
    "small",
    "sprig",
    "sprigs",
    "stalk",
    "stalks",
    "stick",
    "sticks",
    "tablespoon",
    "tablespoons",
    "teaspoon",
    "teaspoons",
    "whole"
  ];

  public bo_global_cuisines = [
    "Afghan",
    "African",
    "American",
    "American-South",
    "Asian",
    "Australian",
    "Brazilian",
    "Cajun",
    "Canadian",
    "Caribbean",
    "Chinese",
    "Croatian",
    "Cuban",
    "Dessert",
    "Eastern European",
    "English",
    "French",
    "German",
    "Greek",
    "Hawaiian",
    "Hungarian",
    "India",
    "Indian",
    "Irish",
    "Italian",
    "Japanese",
    "Jewish",
    "Korean",
    "Latin",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Moroccan",
    "Polish",
    "Russian",
    "Scandanavian",
    "Seafood",
    "Southern",
    "Southwestern",
    "Spanish",
    "Tex-Mex",
    "Thai",
    "Vegan",
    "Vegetarian",
    "Vietnamese"
  ];

  public bo_global_ingredients_edible_only = [
    "1% low-fat milk",
    "2% Milk",
    "Abalone",
    "Acorn squash",
    "All purpose flour",
    "Almond Milk",
    "Almonds",
    "American cheese",
    "Anchovies",
    "Andouille sausage",
    "Angel Hair",
    "Apple Cider",
    "Apple Juice",
    "Apple",
    "Apples",
    "Applesauce",
    "Apricot nectar",
    "Apricot",
    "Arborio Rice",
    "Artichoke hearts",
    "Artichokes",
    "Asparagus",
    "Avocado",
    "Avocados",
    "Baby corn",
    "Baby new potatoes",
    "Baby spinach",
    "Baby wipes",
    "Bacon",
    "Baguette",
    "Baked potatoes",
    "Baking potatoes",
    "Baking powder",
    "Baking soda",
    "Balsamic Vinegar",
    "Bananas",
    "Barbeque sauce",
    "Basil fresh",
    "Basil",
    "Bay leaf",
    "Bay leaves",
    "Beef bouillon cube",
    "Beef broth",
    "Beef stock",
    "Beef tenderloin roast",
    "Beef Tenderloin",
    "Beef top sirloin steak",
    "Beef",
    "Beet",
    "Bell pepper",
    "Bisquick",
    "Black beans",
    "Black olives",
    "Black pepper",
    "Black pitted olives",
    "Black tea leaves",
    "Black-eyed peas",
    "Blue cheese dressing",
    "Blue Cheese",
    "Blueberries",
    "blueberry muffin mix",
    "bone-in beef short ribs",
    "Bone-in chicken thighs",
    "Boneless beef top sirloin",
    "Boneless brook trout",
    "Boneless chicken breast halves",
    "Boneless chicken breasts",
    "Boneless chicken",
    "Boneless chuck",
    "Boneless pork shoulder roast",
    "Boneless pork shoulder",
    "Boston lettuce",
    "Bow tie pasta",
    "Bran",
    "Brandy",
    "Brats",
    "Bread crumbs",
    "Bread",
    "Broccoli Florets",
    "Broccoli",
    "Brook trout",
    "Brown rice",
    "Brown sugar",
    "Brownie mix",
    "Burmuda Onion",
    "Butter",
    "Buttermilk",
    "Butternut squash",
    "Cabbage",
    "Cream of Mushroom Soup",
    "Tomato Soup",
    "Can goose liver pate",
    "Canadian bacon",
    "Candy",
    "Canned mushrooms stems and pieces",
    "Canned peaches",
    "Canola mayonnaise",
    "Canola Oil",
    "Canteloupe",
    "Capers",
    "Cardamom",
    "Carrot",
    "Cauliflower",
    "Cayenne pepper",
    "Cayenne",
    "Celery chopped",
    "Celery hearts",
    "Celery seed",
    "celery stalks",
    "Celery",
    "center-cut bacon",
    "Champagne",
    "Cheddar cheese",
    "Cheerios",
    "Cheese Sticks",
    "Cheese",
    "Cherry tomatoes",
    "Chicken bouillon",
    "Chicken breast halves",
    "Chicken breast",
    "Chicken breasts boneless and skinless",
    "Chicken broth",
    "chicken cutlets",
    "Chicken drumsticks",
    "Chicken mince",
    "Chicken Nuggets",
    "Chicken Stock",
    "Chicken whole",
    "Chicken wings",
    "Chicken",
    "chiles",
    "Chili paste",
    "Chili pepper",
    "Chili peppers",
    "Chili powder",
    "Chinese sausages",
    "Chinese sesame paste",
    "Chipotle Powder",
    "Chipotles, canned in adobo sauce",
    "Chives",
    "Chocolate chips",
    "Chocolate ice cream",
    "Chocolate",
    "chopped bok choy",
    "Chutney",
    "Ciabatta bread",
    "Cider Vinegar",
    "Cilantro",
    "Cinnamon stick",
    "Cinnamon",
    "Clam juice",
    "Clams",
    "Club Soda",
    "Coarse Salt",
    "Cocoa",
    "Coconut",
    "Coffee",
    "Cognac",
    "Cold cooked salmon",
    "Condensed milk",
    "Confectioners Sugar",
    "Cooked ham",
    "Cooking Spray",
    "Coriander sprigs",
    "Corn oil",
    "Corn on the cob",
    "Corn starch",
    "Corn tortilla chips",
    "Corn",
    "Cornflour",
    "Cornmeal",
    "Cornstarch",
    "Cottage cheese",
    "Cracked wheat",
    "Cracker Barrel Cheese",
    "Cranberries",
    "Cranberry Juice",
    "Crawfish",
    "Cream cheese",
    "Cream of Chicken Soup",
    "Cream of Tartar",
    "Cream",
    "Creamed Corn",
    "Creme Fraiche",
    "Cremini Mushrooms",
    "Creole mustard",
    "Croutons",
    "Crushed tomatoes",
    "Cubed chicken",
    "Cucumber",
    "Cumin",
    "Curry powder",
    "Cut Watermelon",
    "Dark chocolate",
    "Dark sesame oil",
    "Dark soy sauce",
    "Dates",
    "Deli Ham",
    "Deli Turkey",
    "Diced tomatoes",
    "Dijon mustard",
    "Dill pickle",
    "Dill",
    "Doughnuts",
    "Dressing",
    "Dried basil",
    "Dried chiles",
    "Dried Great Northern beans",
    "Dried oregano",
    "Dried Pinto Beans",
    "Dried Red Pepper",
    "Dried rosemary",
    "Dried Tarragon",
    "Dried thyme",
    "Dried wheat noodles",
    "Dry bread crumbs",
    "dry breadcrumbs",
    "Dry mustard",
    "Dry red wine",
    "Dry roasted pecans",
    "Dry sherry",
    "Dry vermouth",
    "Dry white wine",
    "Dumplings",
    "Egg whites",
    "Egg yolks",
    "Egg",
    "Eggplant",
    "Eggs",
    "Macaroni",
    "Enchilada sauce",
    "Endive",
    "English muffins",
    "English Peas",
    "Envelopes",
    "Evaporated milk",
    "Extra virgin olive oil",
    "Extra Wide Egg Noodles",
    "fava beans",
    "Fennel Seeds",
    "Fennel",
    "fermented black beans",
    "Feta cheese",
    "Filet Mignon",
    "Finely chopped onions",
    "Fire-roasted tomatoes",
    "Fish bouillon",
    "Fish stock",
    "Fish",
    "Five spices powder",
    "Florentine fennel",
    "Flounder",
    "Flour tortillas",
    "Flour",
    "French bread",
    "French sandwich rolls",
    "Fresh basil",
    "Fresh blueberries",
    "Fresh chives",
    "Fresh Cilantro",
    "Fresh Coriander",
    "Fresh corn kernels",
    "Fresh cranberries",
    "Fresh dill",
    "fresh green beans",
    "Fresh green chilli",
    "Fresh Italian parsley",
    "Fresh lemon juice",
    "Fresh lemon",
    "Fresh lump Crabmeat",
    "Fresh mint",
    "Fresh Morel Mushrooms",
    "Fresh mozzarella cheese",
    "Fresh mung bean sprouts",
    "Fresh mushrooms",
    "Fresh mushrooms, chopped",
    "Fresh okra",
    "Fresh oregano",
    "Fresh parsley chopped",
    "Fresh parsley",
    "Fresh rosemary",
    "Fresh sage minced",
    "Fresh sage",
    "Fresh shiitake",
    "Fresh Spinach",
    "Fresh Tarragon",
    "Fresh Thyme",
    "Freshly ground pepper",
    "Frozen cheese pizza",
    "Frozen corn",
    "frozen french fries",
    "Frozen lima beans",
    "Frozen pastry shells",
    "Frozen Peas",
    "Frozen petite peas",
    "Frozen Shrimp",
    "Frozen sliced okra",
    "Frozen vegetables",
    "Frozen whole strawberries",
    "garam masala",
    "Garlic Bread",
    "Garlic cloves",
    "Garlic powder",
    "Garlic Salt",
    "Garlic",
    "Gin",
    "Ginger minced",
    "Ginger roots",
    "Ginger",
    "Gingersnap cookies",
    "Gnocchi",
    "Goat Cheese",
    "Golden raisins",
    "Goose liver pate",
    "Graham crackers",
    "Grainy mustard",
    "Granulated sugar",
    "Grape leaves",
    "Grape Nuts",
    "Great Northern beans",
    "Greek olives",
    "Green Beans",
    "Green chili",
    "Green Curry Paste",
    "Green jalapeno pepper",
    "Green onion",
    "Green onions",
    "Green or Red Curry Paste",
    "Green pepper",
    "Greens",
    "Grey Poupon",
    "Grits",
    "Ground beef",
    "Ground black pepper",
    "Ground Cardamom",
    "Ground cayenne pepper",
    "Ground chuck",
    "Ground Coriander",
    "Ground cumin",
    "Ground Flaxseed",
    "Ground mustard",
    "Ground pork",
    "Ground turkey",
    "Ground white pepper",
    "Gruyere",
    "Half-and-half cream",
    "Ham",
    "Hamburger",
    "Hamburgers",
    "Hard boiled eggs",
    "Hash Browns",
    "Heavy cream",
    "Heavy whipping cream",
    "Herb seasoned stuffing mix",
    "Hoisin sauce",
    "Hollandaise sauce mix",
    "Honey Wheatberry Bread",
    "Honey",
    "Horseradish",
    "Hot Dogs",
    "hot or sweet turkey italian sausage",
    "Hot pepper sauce",
    "Hotdogs",
    "Ice water",
    "Ice",
    "Iced Tea",
    "Imported Swiss",
    "Instant lemon pudding",
    "Instant Oatmeal",
    "Italian Bread",
    "Italian dressing",
    "Italian parsley leaves",
    "Italian parsley",
    "Italian seasoning",
    "Jalapeno Pepper",
    "Jalapeno Peppers",
    "Jalapenos",
    "Kahlua",
    "Kale Salad",
    "Kale",
    "Ketchup",
    "Kidney beans",
    "King salmon",
    "Kirin",
    "Kosher Salt",
    "Kraft Natural blue cheese",
    "Lamb loin chops",
    "Lamb",
    "Lard",
    "Lavendar",
    "Lean ground chicken",
    "Lean ground pork or chicken",
    "Lean smoked slab bacon",
    "Lemon Grass",
    "Lemon Juice",
    "Lemon pepper",
    "Lemon wedges",
    "Lemon",
    "lemonade",
    "Lemons",
    "Lettuce",
    "Life",
    "Light brown sugar",
    "light coconut milk",
    "Light Corn Syrup",
    "Light cream cheese",
    "Light cream",
    "Light sour cream",
    "Lime Juice",
    "Lime zest",
    "Lime",
    "Lobster tails",
    "Lobster",
    "Long grain rice",
    "Low fat mayonnaise",
    "Low fat plain yogurt",
    "Low sodium chicken broth",
    "lower-sodium turkey",
    "Lowfat Milk",
    "Mac & Cheese",
    "Macademia nuts",
    "Madeira",
    "Mandarin Oranges",
    "Mango",
    "Maple Syrup",
    "Margarine",
    "Marinade",
    "marinara sauce",
    "Marinated artichoke hearts",
    "Marsala",
    "Marshmallows",
    "Mayonnaise",
    "Meat",
    "meatballs",
    "Meatloaf",
    "Melted Butter",
    "Mexican Rice",
    "Mexican",
    "Milk chocolate",
    "Milk",
    "Minced parsley",
    "Mint leaves",
    "Mint",
    "Mirin",
    "Mixed greens",
    "Molasses",
    "Monkfish",
    "Monterey jack cheese",
    "Morel Mushrooms",
    "Mozzarella grated",
    "Mozzarella",
    "Mushroom caps",
    "Mushroom",
    "Mushrooms",
    "Mustard Greens",
    "Mustard seed",
    "Mustard",
    "No-boil lasagna noodles",
    "Noodle",
    "Noodles",
    "Nutmeg",
    "Oil",
    "oil-packed sun-dried tomatoes",
    "Olive oil",
    "Olives",
    "Onion dip",
    "Onion powder",
    "Onion",
    "Onions",
    "Orange juice",
    "Orange peel",
    "Orange zest",
    "Orange",
    "Oranges",
    "Oregano",
    "Oriental sesame oil",
    "Oyster mushrooms",
    "Oyster Sauce",
    "Oysters",
    "Pace Salsa",
    "Pancake syrup",
    "Pancetta",
    "Paprika",
    "Parmesan cheese",
    "Parmesan grated",
    "Parmesan",
    "Parmigiano-Reggiano cheese",
    "Parmigiano-Reggiano",
    "Parsley",
    "Part Skim Mozzarella Cheese",
    "Pasta",
    "Pea Pods",
    "Peach jam",
    "Peaches in fruit juice",
    "Peaches",
    "Peanut butter",
    "Peanut oil",
    "Peas",
    "Pecans",
    "Penne pasta",
    "Pepper",
    "Peppercorns",
    "Pepperoni",
    "Pesto sauce",
    "Petite-diced tomatoes",
    "Pheasant",
    "Pie crust",
    "Pimento",
    "Pimiento-stuffed olives",
    "Pine nuts",
    "Pineapple juice",
    "Pineapple tidbits",
    "Pineapple",
    "Pinot Noir",
    "Pinto beans",
    "Pizza dough",
    "Pizza Sauce",
    "Plain Couscous",
    "Plum tomatoes",
    "Pomegranate",
    "Poppy seed salad dressing",
    "Pork chops",
    "Pork shoulder roast",
    "Pork",
    "Portabella Mushrooms",
    "Porterhouse Steak",
    "Portobello mushroom",
    "Portobello mushrooms cut into 1-inch pieces",
    "Potato chips",
    "Potato",
    "Potatoes",
    "Poultry Seasoning",
    "Powdered sugar",
    "Prawns",
    "Prosciutto",
    "Provolone",
    "Quick oatmeal",
    "Quick-rise active dry yeast",
    "Radishes",
    "Rainbow Trout Fillets",
    "Rainbow Trout",
    "Raisin Bran",
    "Raisins",
    "Raspberries in apple juice",
    "Raspberry Liqueur",
    "Ravioli",
    "Red bell pepper",
    "Red chile",
    "Red curry paste",
    "Red Devil Hot Sauce",
    "Red grapes",
    "Red Jalapeno",
    "Red Maine Potatoes",
    "Red onion",
    "Red pepper flakes",
    "Red pepper",
    "Red peppers",
    "Red potatoes",
    "Red wine vinegar",
    "Reduced Fat Cheddar cheese",
    "Reduced fat cream cheese",
    "Reduced fat sour cream",
    "Reduced-sodium soy sauce",
    "rib eye steaks",
    "Rice noodles",
    "rice sticks",
    "Rice vinegar",
    "Rice wine",
    "Rice",
    "Ricotta Cheese part skim",
    "Ripe olives",
    "Roasted Chicken",
    "Roasted Potatoes",
    "Roma Tomatoes",
    "Romaine",
    "Root Beer",
    "Roquefort cheese",
    "Roquefort",
    "Rotini",
    "Rotisserie Chicken",
    "Russet potatoes",
    "Sage",
    "Salad",
    "Salami",
    "Salmon filets",
    "Salmon",
    "Salsa",
    "Salt and pepper",
    "Salt",
    "Sandwiches",
    "Sausage",
    "Scallion",
    "Scallions",
    "Scallops",
    "Sea Salt",
    "Sea scallops",
    "Seasonal melon",
    "Self raising flour",
    "Semisweet chocolate",
    "Serrano chiles",
    "Sesame Oil",
    "Sesame seeds",
    "Sesame tahini",
    "Shallot",
    "Shallots minced",
    "Shallots",
    "Shao Hsing wine",
    "Sharp Cheddar cheese",
    "shell pasta",
    "Sherry",
    "shiitake mushroom caps",
    "Shiitake mushrooms",
    "Shiraz",
    "Shortbread",
    "Shortening",
    "Shredded cheese",
    "Shrimp",
    "Sirloin Or Flank Steak",
    "Skim milk",
    "Skinless chicken breasts",
    "Sliced almonds",
    "Sliced Shallots",
    "Smoked salmon",
    "Smoked sausages",
    "Snow peas",
    "Soft shelled crabs",
    "Sole",
    "Soup",
    "Sour cream",
    "Southern comfort",
    "Soy sauce",
    "Spaghetti Sauce",
    "Spaghetti",
    "Spam",
    "Spanish olive oil",
    "Spareribs",
    "Spinach Salad",
    "Spinach",
    "Squash",
    "Star anise",
    "Steak",
    "Steel-Cut Oats",
    "Stew meat",
    "Strawberries",
    "Strawberry",
    "strozzapreti",
    "Stuffed olives",
    "Sugar cube",
    "Sugar Snap Peas",
    "Sugar",
    "Sun-dried tomatoes",
    "sunflower butter",
    "Sunflower oil",
    "Sweet butter",
    "Sweet onion",
    "Sweet pepper",
    "Sweet pickle",
    "Sweet potatoes",
    "Sweetened Condensed Milk",
    "Sweet-Sour Sauce",
    "Swiss Cheese",
    "Swiss",
    "Tabasco sauce",
    "Taco Shells",
    "Tamari soy sauce",
    "Tapenade",
    "Tarragon",
    "Tea",
    "Tequila",
    "Teriyaki sauce",
    "thick tomato slices",
    "Thin Spaghetti",
    "Thousand island sauce",
    "Thyme",
    "Toasted bread crumbs",
    "Toasted sesame oil",
    "Tofu",
    "Tomato juice",
    "Tomato paste",
    "Tomato puree",
    "Tomato sauce",
    "Tomato",
    "Tomatoes",
    "Toothpaste",
    "Trout fillets",
    "Trout",
    "Turmeric",
    "Tuna",
    "Turkey pepperoni",
    "turkey slices",
    "Turkey",
    "Turmeric",
    "Udon Noodles",
    "Unsalted butter cold",
    "Unsalted butter",
    "Unsalted roasted peanuts",
    "Unsweetened chocolate",
    "Vanilla extract",
    "Vanilla Ice Cream",
    "Vanilla",
    "vegetable broth",
    "Vegetable oil",
    "Vegetables",
    "Vinegar",
    "Waffles",
    "Walnut oil",
    "Walnuts broken",
    "Walnuts",
    "Water chestnuts",
    "Water",
    "Watermelon",
    "Wheat hamburger buns",
    "Whipping cream",
    "Whiskey",
    "White chocolate",
    "White Fungus",
    "White Onion",
    "White pepper",
    "white rice cooked",
    "White rice",
    "White wine vinegar",
    "White wine",
    "Whole dressed trout",
    "Whole grain mustard",
    "Whole milk",
    "Whole Tomatoes",
    "Whole trout",
    "Whole wheat bread",
    "Whole wheat English Muffins",
    "Whole wheat pasta",
    "Whole-wheat flour",
    "Wine vinegar",
    "Wine",
    "Worcestershire sauce",
    "Yeast active dry yeast",
    "Yeast",
    "Yellow Beans",
    "Yellow mustard",
    "Yellow onion",
    "Yellow pepper",
    "Yellow split peas",
    "Yellow Squash",
    "Yogurt",
    "Yukon gold potatoes",
    "Zatar",
    "Ziti",
    "Zucchini"
  ];


  ingredients_edible = [
    {name:"abalone",img:"abalone.jpg"},
    {name:"achee",img:"ackee.jpg"},
    {name:"alcohol",img:"alcohol.jpg"},
    {name:"all-purpose flour",img:"flourcup.jpg"},
    {name:"allspice",img:"allspice2.jpg"},
    {name:"almond",img:"almond.jpg"},
    {name:"almond extract",img:"almond2.jpg"},
    {name:"amaretto",img:"amaretto.jpg"},
    {name:"anchovies",img:"anchovy.jpg"},
    {name:"anchovy",img:"anchovy.jpg"},
    {name:"angel hair",img:"angelhair.jpg"},
    {name:"anise",img:"anise.jpg"},
    {name:"apple",img:"apple2.jpg"},
    {name:"apples",img:"apple2.jpg"},
    {name:"apple juice",img:"applejuice.jpg"},
    {name:"apricot",img:"apricot.jpg"},
    {name:"artichoke",img:"artichoke.jpg"},
    {name:"arugula",img:"arugula.jpg"},
    {name:"asiago cheese",img:"asiagocheese.jpg"},
    {name:"asparagus",img:"asparagus.jpg"},
    {name:"avocado",img:"avocado.jpg"},
    {name:"baby spinach",img:"babyspinach2.jpg"},
    {name:"bacon",img:"bacon.jpg"},
    {name:"bagel",img:"bagel.jpg"},
    {name:"baking powder",img:"bakingpowder.jpg"},
    {name:"baking soda",img:"bakingpowder.jpg"},
    {name:"balsamic vinegar",img:"balsamicvinegar.jpg"},
    {name:"banana",img:"banana2.jpg"},
    {name:"barbecue sauce",img:"barbecuesauce.jpg"},
    {name:"barley",img:"barley.jpg"},
    {name:"basil",img:"basil.jpg"},
    {name:"bay leaves",img:"bayleaves.jpg"},
    {name:"bean sprouts",img:"beansprouts.jpg"},
    {name:"beans",img:"beansmixed.jpg"},
    {name:"beans",img:"beansmixed.jpg"},
    {name:"beef",img:"beef.jpg"},
    {name:"beer",img:"beer3.jpg"},
    {name:"beet",img:"beet.jpg"},
    {name:"beets",img:"beet.jpg"},
    {name:"bell pepper",img:"bellpepper.jpg"},
    {name:"ham",img:"ham.jpg"},
    {name:"bisquick",img:"bisquick.jpg"},
    {name:"black bean",img:"blackbean.jpg"},
    {name:"black beans",img:"blackbean.jpg"},
    {name:"black pepper",img:"pepper.jpg"},
    {name:"blackberries",img:"blackberries.jpg"},
    {name:"black-eyed peas",img:"blackeyedpeas.jpg"},
    {name:"blanch",img:"blanch.jpg"},
    {name:"blender",img:"blender.jpg"},
    {name:"blue cheese",img:"bluecheese.jpg"},
    {name:"blueberries",img:"blueberries.jpg"},
    {name:"bok choy",img:"bokchoy.jpg"},
    {name:"bosc pear",img:"boscpear.jpg"},
    {name:"bouillon",img:"bouillon.jpg"},
    {name:"brandy",img:"brandy.jpg"},
    {name:"bread crumbs",img:"breadcrumbs.jpg"},
    {name:"bread machine",img:"breadmachine.jpg"},
    {name:"brie",img:"brie.jpg"},
    {name:"broccoli",img:"broccoli.jpg"},
    {name:"broccoli rabe",img:"broccolirabe.jpg"},
    {name:"brown rice",img:"brownrice.jpg"},
    {name:"brown sugar",img:"brownsugar.jpg"},
    {name:"brussels sprouts",img:"brusselssprouts.jpg"},
    {name:"bucatini",img:"bucatini.jpg"},
    {name:"butter",img:"butter2.jpg"},
    {name:"buttermilk",img:"buttermilk.jpg"},
    {name:"butternut squash",img:"butternutsquash2.jpg"},
    {name:"cabbage",img:"cabbage.jpg"},
    {name:"calamari",img:"calamari.jpg"},
    {name:"cannellini bean",img:"cannellinibean.jpg"},
    {name:"canola oil",img:"canola.jpg"},
    {name:"cantaloupe",img:"cantaloupe.jpg"},
    {name:"caper",img:"capers.jpg"},
    {name:"caraway seed",img:"caraway.jpg"},
    {name:"cardamom",img:"cardamom.jpg"},
    {name:"carrot",img:"carrots.jpg"},
    {name:"carrots",img:"carrots.jpg"},
    {name:"cashew",img:"cashew.jpg"},
    {name:"cauliflower",img:"cauliflower.jpg"},
    {name:"caviar",img:"caviar.jpg"},
    {name:"cayenne",img:"groundredpepper.jpg"},
    {name:"celeriac",img:"celeriac.jpg"},
    {name:"celery",img:"celery.jpg"},
    {name:"celery seed",img:"celseed.jpg"},
    {name:"chai",img:"chai.jpg"},
    {name:"champagne",img:"champagne.jpg"},
    {name:"chayote",img:"chayote.jpg"},
    {name:"cheddar",img:"cheddar.jpg"},
    {name:"cheddar cheese",img:"cheddar.jpg"},
    {name:"cherries",img:"cherries.jpg"},
    {name:"cherry tomatoes",img:"cherrytomato.jpg"},
    {name:"chervil",img:"chervil.jpg"},
    {name:"chestnut",img:"chestnut.jpg"},
    {name:"chevre",img:"goatcheesesalad.jpg"},
    {name:"chick peas",img:"chickpeas.jpg"},
    {name:"chicken",img:"chicken.jpg"},
    {name:"chicken breast",img:"chickenbreast.jpg"},
    {name:"chicken broth",img:"chickenbroth.jpg"},
    {name:"chicken stock",img:"chickenstock.jpg"},
    {name:"chile",img:"chile.jpg"},
    {name:"chili oil",img:"chilioil.jpg"},
    {name:"chili paste",img:"chilepaste.jpg"},
    {name:"chili powder",img:"chilipowder.jpg"},
    {name:"chives",img:"chives.jpg"},
    {name:"chocolate",img:"chocochips.jpg"},
    {name:"chutney",img:"chutney.jpg"},
    {name:"cider vinegar",img:"cidervin.jpg"},
    {name:"cilantro",img:"cilantro.jpg"},
    {name:"cinnamon",img:"cinnamon.jpg"},
    {name:"clams",img:"clams.jpg"},
    {name:"cloves",img:"cloves.jpg"},
    {name:"cocoa",img:"cocoa.jpg"},
    {name:"coconut",img:"coconut.jpg"},
    {name:"coconut milk",img:"coconut_milk.jpg"},
    {name:"cod",img:"cod.jpg"},
    {name:"coffee",img:"coffee.jpg"},
    {name:"cooking oil",img:"cookingoil.jpg"},
    {name:"cooking spray",img:"pans.jpg"},
    {name:"coriander",img:"coriander.jpg"},
    {name:"corn",img:"corn3.jpg"},
    {name:"corn starch",img:"cornstarch.jpg"},
    {name:"corned beef",img:"beef.jpg"},
    {name:"cornmeal",img:"cornbread.jpg"},
    {name:"cornstarch",img:"cornstarch.jpg"},
    {name:"cottage cheese",img:"cottagecheese.jpg"},
    {name:"couscous",img:"couscous.jpg"},
    {name:"crab",img:"crab.jpg"},
    {name:"cranberries",img:"cranberry.jpg"},
    {name:"cranberry",img:"cranberry.jpg"},
    {name:"crayfish",img:"crayfish.jpg"},
    {name:"cream",img:"whipping_cream.jpg"},
    {name:"cream cheese",img:"creamcheese.jpg"},
    {name:"cream of mushroom",img:"creamofmushroom.jpg"},
    {name:"cream of tartar",img:"meringue.jpg"},
    {name:"creme fraiche",img:"cremefraiche.jpg"},
    {name:"crouton",img:"croutons.jpg"},
    {name:"cucumber",img:"cucumber.jpg"},
    {name:"cumin",img:"cumin.jpg"},
    {name:"curry",img:"curry.jpg"},
    {name:"daikon",img:"daikon.jpg"},
    {name:"dal",img:"dal.jpg"},
    {name:"dates",img:"dates2.jpg"},
    {name:"onion",img:"onion.jpg"},
    {name:"diet cola",img:"dietcola.jpg"},
    {name:"dijon mustard",img:"dijon.jpg"},
    {name:"dill",img:"dill.jpg"},
    {name:"duck",img:"duckbreast.jpg"},
    {name:"dukka",img:"dukkah2.jpg"},
    {name:"egg",img:"eggs.jpg"},
    {name:"eggplant",img:"eggplant.jpg"},
    {name:"eggs",img:"eggs.jpg"},
    {name:"endive",img:"belgianendive.jpg"},
    {name:"escargot",img:"escargot.jpg"},
    {name:"evaporated milk",img:"evapmilk.jpg"},
    {name:"extra virgin olive oil",img:"evoo.jpg"},
    {name:"farfalle",img:"farfalle.jpg"},
    {name:"fava bean",img:"favabean.jpg"},
    {name:"fennel",img:"fennel.jpg"},
    {name:"feta",img:"feta.jpg"},
    {name:"fig",img:"figs.jpg"},
    {name:"figs",img:"figs.jpg"},
    {name:"fish",img:"fish.jpg"},
    {name:"fish sauce",img:"phadthai.jpg"},
    {name:"flour",img:"flour.jpg"},
    {name:"food coloring",img:"foodcolor.jpg"},
    {name:"food processor",img:"foodprocessor.jpg"},
    {name:"fruit",img:"fruits.jpg"},
    {name:"garlic",img:"garlic.jpg"},
    {name:"gelatin",img:"gelatin.jpg"},
    {name:"ginger",img:"ginger.jpg"},
    {name:"ginger powder",img:"groundginger.jpg"},
    {name:"ginger root",img:"ginger.jpg"},
    {name:"gluten",img:"gluten.jpg"},
    {name:"goat cheese",img:"goatcheesesalad.jpg"},
    {name:"goose",img:"goose.jpg"},
    {name:"gorgonzola",img:"gorgonzola.jpg"},
    {name:"gouda",img:"gouda2.jpg"},
    {name:"graham cracker",img:"grahamcracker1.jpg"},
    {name:"grand marnier",img:"grandmarnier.jpg"},
    {name:"granny smith",img:"grannysmith.jpg"},
    {name:"grape leaves",img:"grapeleaves.jpg"},
    {name:"grapefruit",img:"grapefruit.jpg"},
    {name:"grapes",img:"grapes.jpg"},
    {name:"green bell pepper",img:"greenbellpepper.jpg"},
    {name:"green onion",img:"greenonion.jpg"},
    {name:"greens",img:"broccolirabe.jpg"},
    {name:"grill",img:"grill.jpg"},
    {name:"grits",img:"grits.jpg"},
    {name:"ground beef",img:"groundbeef2.jpg"},
    {name:"ground pepper",img:"groundpepper.jpg"},
    {name:"ground turkey",img:"groundturkey.jpg"},
    {name:"habanero pepper",img:"habanero.jpg"},
    {name:"half and half",img:"halfandhalf.jpg"},
    {name:"hazelnut",img:"hazelnut1.jpg"},
    {name:"herb",img:"herb.jpg"},
    {name:"herbes de provence",img:"herbesdeprovence.jpg"},
    {name:"hoisin sauce",img:"hoisinsauce.jpg"},
    {name:"honey",img:"honey.jpg"},
    {name:"horseradish",img:"horseradish.jpg"},
    {name:"italian parsley",img:"italparsley.jpg"},
    {name:"italian seasoning",img:"italianseason.jpg"},
    {name:"jalapeno",img:"jalapeno.jpg"},
    {name:"jerk spice",img:"jerkshrimp.jpg"},
    {name:"jerusalem artichoke",img:"jerusalem_artichoke.jpg"},
    {name:"jicama",img:"jicama.jpg"},
    {name:"kale",img:"kale.jpg"},
    {name:"karo syrup",img:"pecanpie.jpg"},
    {name:"ketchup",img:"keylimepie.jpg"},
    {name:"kiwi",img:"kiwi.jpg"},
    {name:"kosher salt",img:"koshersalt.jpg"},
    {name:"ladyfingers",img:"ladyfingers.jpg"},
    {name:"lamb",img:"lamb.jpg"},
    {name:"lard",img:"lard.jpg"},
    {name:"leek",img:"leeks.jpg"},
    {name:"leeks",img:"leeks.jpg"},
    {name:"lemon",img:"lemons.jpg"},
    {name:"lemon grass",img:"lemongrass.jpg"},
    {name:"lentil",img:"lentil.jpg"},
    {name:"lettuce",img:"lettuce.jpg"},
    {name:"lima bean",img:"limabean.jpg"},
    {name:"lime",img:"lime.jpg"},
    {name:"lime juice",img:"limejuice.jpg"},
    {name:"liver",img:"liver.jpg"},
    {name:"lobster",img:"lobster.jpg"},
    {name:"mace",img:"pastry.jpg"},
    {name:"mahi mahi",img:"mahimahi.jpg"},
    {name:"mango",img:"mango.jpg"},
    {name:"mangos",img:"mango.jpg"},
    {name:"manicotti",img:"manicotti.jpg"},
    {name:"maple syrup",img:"maplesyrup.jpg"},
    {name:"margarine",img:"margarine.jpg"},
    {name:"marinade",img:"marinade.jpg"},
    {name:"marjoram",img:"marjoram.jpg"},
    {name:"marsala",img:"marsalachicken.jpg"},
    {name:"marshmallow",img:"marshmallow.jpg"},
    {name:"marzipan",img:"marzipanfruits.jpg"},
    {name:"masa",img:"masa2.jpg"},
    {name:"mascarpone",img:"mascarpone.jpg"},
    {name:"mayo",img:"mayonnaise.jpg"},
    {name:"mayonnaise",img:"mayonnaise.jpg"},
    {name:"melon",img:"melon.jpg"},
    {name:"mesclun",img:"mesclun.jpg"},
    {name:"milk",img:"milk.jpg"},
    {name:"mint",img:"mint.jpg"},
    {name:"mirin",img:"mirin.jpg"},
    {name:"miso",img:"misosoup.jpg"},
    {name:"mizuna",img:"mizuna.jpg"},
    {name:"molasses",img:"molasses.jpg"},
    {name:"mother sauces",img:"mothersauces.jpg"},
    {name:"mozzarella",img:"mozzarella.jpg"},
    {name:"mushroom",img:"mushroom-sing.jpg"},
    {name:"mushrooms",img:"mushroom.jpg"},
    {name:"mussels",img:"mussels.jpg"},
    {name:"mustard",img:"mustard.jpg"},
    {name:"nectarine",img:"nectarine.jpg"},
    {name:"neufchatel cheese",img:"neufchatel.jpg"},
    {name:"nonreactive",img:"nonreactive.jpg"},
    {name:"nori",img:"nori.jpg"},
    {name:"nutmeg",img:"nutmeg.jpg"},
    {name:"oats",img:"oats.jpg"},
    {name:"okra",img:"okra.jpg"},
    {name:"olive",img:"olive.jpg"},
    {name:"olive oil",img:"oliveoil2.jpg"},
    {name:"onion powder",img:"onionpowder.jpg"},
    {name:"orange",img:"orange.jpg"},
    {name:"orange juice",img:"orangejuice.jpg"},
    {name:"oranges",img:"orange.jpg"},
    {name:"oregano",img:"oregano.jpg"},
    {name:"organic",img:"organic.jpg"},
    {name:"orzo",img:"orzo.jpg"},
    {name:"oyster",img:"oysters.jpg"},
    {name:"oyster sauce",img:"oystersauce.jpg"},
    {name:"pancetta",img:"pancetta.jpg"},
    {name:"papaya",img:"papaya.jpg"},
    {name:"paprika",img:"paprika.jpg"},
    {name:"parmesan",img:"parmesan.jpg"},
    {name:"parmigiano-reggiano",img:"parmesan.jpg"},
    {name:"parsley",img:"parsley.jpg"},
    {name:"parsnips",img:"parsnips.jpg"},
    {name:"pasta",img:"pasta.jpg"},
    {name:"pawpaw",img:"papaya2.jpg"},
    {name:"peach",img:"peach.jpg"},
    {name:"peanut butter",img:"peanutbutter.jpg"},
    {name:"pear",img:"pear.jpg"},
    {name:"peas",img:"peapod.jpg"},
    {name:"pecan",img:"pecans.jpg"},
    {name:"pecans",img:"pecans.jpg"},
    {name:"penne",img:"penne.jpg"},
    {name:"peppercorn",img:"peppercorn_black.jpg"},
    {name:"persimmons",img:"persimmons.jpg"},
    {name:"phyllo",img:"phyllo.jpg"},
    {name:"pimento",img:"pimento.jpg"},
    {name:"pine nut",img:"pinenut.jpg"},
    {name:"pineapple",img:"pineapple.jpg"},
    {name:"pistachio",img:"pistachio.jpg"},
    {name:"pita",img:"pita.jpg"},
    {name:"plum",img:"plum.jpg"},
    {name:"plum tomatoes",img:"plumtomatoes.jpg"},
    {name:"polenta",img:"polenta.jpg"},
    {name:"pomegranate",img:"pomegranate.jpg"},
    {name:"poppy seed",img:"poppyseeds.jpg"},
    {name:"pork",img:"pork.jpg"},
    {name:"pork tenderloin",img:"porktenderloin.jpg"},
    {name:"port",img:"port.jpg"},
    {name:"potato",img:"potato2.jpg"},
    {name:"powdered sugar",img:"powderedsugar.jpg"},
    {name:"prosciutto",img:"prosciutto.jpg"},
    {name:"provolone",img:"provolone.jpg"},
    {name:"prune",img:"prunes.jpg"},
    {name:"puff pastry",img:"puffpastry.jpg"},
    {name:"pumpkin",img:"pumpkin.jpg"},
    {name:"queso fresco",img:"cheesepepper.jpg"},
    {name:"rabbit",img:"rabbit.jpg"},
    {name:"raclette cheese",img:"raclette.jpg"},
    {name:"radicchio",img:"radicchio.jpg"},
    {name:"radish",img:"radish.jpg"},
    {name:"raisins",img:"raisins.jpg"},
    {name:"raspberry",img:"raspberry.jpg"},
    {name:"red bell pepper",img:"redbellpeppers.jpg"},
    {name:"red onion",img:"redonion.jpg"},
    {name:"red pepper flakes",img:"redpepperflakes.jpg"},
    {name:"red wine",img:"redwine2.jpg"},
    {name:"red wine vinegar",img:"redwinevinegar.jpg"},
    {name:"rhubarb",img:"rhubarb.jpg"},
    {name:"rice",img:"rice.jpg"},
    {name:"rice wine vinegar",img:"ricewinevinegar.jpg"},
    {name:"ricotta",img:"ricotta2.jpg"},
    {name:"risotto",img:"risotto.jpg"},
    {name:"romaine",img:"caesarsalad.jpg"},
    {name:"roquefort",img:"roquefort.jpg"},
    {name:"rosemary",img:"rosemary.jpg"},
    {name:"rotini",img:"rotini.jpg"},
    {name:"roux",img:"gumbo.jpg"},
    {name:"saffron",img:"paella.jpg"},
    {name:"sage",img:"sage.jpg"},
    {name:"sake",img:"sake.jpg"},
    {name:"salmon",img:"salmon.jpg"},
    {name:"salt",img:"salt2.jpg"},
    {name:"sangria",img:"sangria.jpg"},
    {name:"sashimi",img:"sashimi.jpg"},
    {name:"sauerkraut",img:"sauerkraut.jpg"},
    {name:"sausage",img:"sausages.jpg"},
    {name:"savory",img:"savory.jpg"},
    {name:"scallion",img:"greenonion.jpg"},
    {name:"scallop",img:"scallop.jpg"},
    {name:"scallops",img:"scallops.jpg"},
    {name:"scotch bonnet chilies",img:"scotchbonnet.jpg"},
    {name:"season",img:"seasoning.jpg"},
    {name:"seasonings",img:"spicejars.jpg"},
    {name:"sesame oil",img:"sesameoil.jpg"},
    {name:"sesame seed",img:"sesame.jpg"},
    {name:"shallot",img:"shallot.jpg"},
    {name:"shellfish",img:"shellfish.jpg"},
    {name:"sherry",img:"sherry.jpg"},
    {name:"shiso",img:"shiso.jpg"},
    {name:"shortening",img:"shortening2.jpg"},
    {name:"shrimp",img:"shrimp.jpg"},
    {name:"simple syrup",img:"mintjulep.jpg"},
    {name:"snap peas",img:"snappeas.jpg"},
    {name:"snow pea",img:"snowpea.jpg"},
    {name:"soba",img:"soba.jpg"},
    {name:"sorbet",img:"sorbet.jpg"},
    {name:"sour cream",img:"shutterstock_62167.jpg"},
    {name:"soy sauce",img:"soysauce.jpg"},
    {name:"soybeans",img:"soybeans.jpg"},
    {name:"spaghetti sauce",img:"spaghettisauce.jpg"},
    {name:"spice",img:"spice.jpg"},
    {name:"spinach",img:"spinach.jpg"},
    {name:"splenda",img:"splenda.jpg"},
    {name:"sprouts",img:"beansprouts.jpg"},
    {name:"squash",img:"squashblossom.jpg"},
    {name:"star anise",img:"staranise.jpg"},
    {name:"steak",img:"steak.jpg"},
    {name:"stilton",img:"stilton.jpg"},
    {name:"stone fruits",img:"stonefruit.jpg"},
    {name:"strawberries",img:"strawberries.jpg"},
    {name:"strawberry",img:"strawberries.jpg"},
    {name:"sugar",img:"sugar.jpg"},
    {name:"sun-dried tomato",img:"sundriedtomato.jpg"},
    {name:"sunflower seeds",img:"sunflowerseeds.jpg"},
    {name:"sushi",img:"sushi.jpg"},
    {name:"sweet peppers",img:"sweetpeppers.jpg"},
    {name:"sweet potato",img:"sweetpotato.jpg"},
    {name:"swiss chard",img:"chard.jpg"},
    {name:"swiss cheese",img:"swisscheese.jpg"},
    {name:"tabasco",img:"tabasco.jpg"},
    {name:"taco seasoning",img:"tacoseasoning.jpg"},
    {name:"tahini",img:"hummus.jpg"},
    {name:"tamarind",img:"tamarind.jpg"},
    {name:"tangelo",img:"tangelo.jpg"},
    {name:"tapioca",img:"tapiocastarch.jpg"},
    {name:"tarragon",img:"tarragon.jpg"},
    {name:"tart",img:"tart.jpg"},
    {name:"tartar sauce",img:"tartarsauce.jpg"},
    {name:"tartlet",img:"tartlet.jpg"},
    {name:"tea",img:"tea.jpg"},
    {name:"tenderloin",img:"tenderloin1.jpg"},
    {name:"tequila",img:"tequila.jpg"},
    {name:"teriyaki sauce",img:"teriyaki.jpg"},
    {name:"thyme",img:"thyme.jpg"},
    {name:"tilapia",img:"tilapia.jpg"},
    {name:"tofu",img:"tofu.jpg"},
    {name:"tomatillo",img:"tomatilla.jpg"},
    {name:"tomato",img:"tomatoes.jpg"},
    {name:"tomato paste",img:"tomatopaste.jpg"},
    {name:"tomatoes",img:"tomatoes.jpg"},
    {name:"tortilla",img:"tortilla2.jpg"},
    {name:"triple sec",img:"margarita.jpg"},
    {name:"trout",img:"trout.jpg"},
    {name:"tuna",img:"tunablackened.jpg"},
    {name:"turkey",img:"turkey.jpg"},
    {name:"turmeric",img:"turmeric.jpg"},
    {name:"turnip",img:"turnip.jpg"},
    {name:"udon",img:"udon.jpg"},
    {name:"vadalia",img:"vidaliaonion.jpg"},
    {name:"vanilla",img:"vanilla.jpg"},
    {name:"veal",img:"veal.jpg"},
    {name:"vegetable oil",img:"vegetableoil.jpg"},
    {name:"velveeta",img:"velveeta.jpg"},
    {name:"venison",img:"venison.jpg"},
    {name:"vermouth",img:"vermouth.jpg"},
    {name:"vinaigrette",img:"vinaigrette.jpg"},
    {name:"vinegar",img:"vinegar.jpg"},
    {name:"vodka",img:"vodka.jpg"},
    {name:"waffle",img:"waffles.jpg"},
    {name:"walla walla onion",img:"wallawallaonion.jpg"},
    {name:"walnut",img:"walnut.jpg"},
    {name:"wasabi",img:"wasabi.jpg"},
    {name:"water chestnut",img:"waterchestnuts.jpg"},
    {name:"watercress",img:"watercress.jpg"},
    {name:"watermelon",img:"watermelon.jpg"},
    {name:"wheat",img:"wheat.jpg"},
    {name:"white chocolate",img:"whitechocolate.jpg"},
    {name:"white pepper",img:"whitepepper.jpg"},
    {name:"white vinegar",img:"whitevinegar.jpg"},
    {name:"white wine",img:"whitewine.jpg"},
    {name:"wild rice",img:"wildrice.jpg"},
    {name:"worcestershire sauce",img:"worcestershiresauce.jpg"},
    {name:"yam",img:"yams.jpg"},
    {name:"yeast",img:"yeast.jpg"},
    {name:"yellow bell pepper",img:"yellowbellpepper.jpg"},
    {name:"yogurt",img:"yogurt.jpg"},
    {name:"zucchini",img:"zucchini.jpg"}
  ]



}
